spring:
  application:
    name: "vibeart-api"

  config:
    import:
      - optional:file:.env[.properties]
      - classpath:application-db.yml
      - classpath:application-logger.yml
      - classpath:application-swagger.yml
      - classpath:application-mb.yml

app:
  code-expiration-time: 15m
  jwt:
    secret: ${JWT_SECRET_KEY}
    access-token-validity: ${JWT_ACCESS_TIME}
    refresh-token-validity: ${JWT_REFRESH_TIME}

server:
  # Слушает любой адрес
  address: 0.0.0.0
